CREATE TABLE population (
	state_id INT  NOT NULL,
	state VARCHAR PRIMARY KEY NOT NULL,
	pop INT
);

CREATE TABLE senator (
	state VARCHAR FOREIGN KEY NOT NULL,
	name VARCHAR NOT NULL,
	party VARCHAR NOT NULL
);

SELECT * FROM population
SELECT * FROM senator